"use client";

import { TrendingUp, Award, Calendar, CheckCircle2 } from "lucide-react";

export interface ImpactSummary {
  id: string;
  score: number;
  metrics: { views?: number; likes?: number; comments?: number };
  generated_at: string;
}

/**
 * ProjectImpactSection — the old /projects/impact/[id] page folded into
 * the project detail page as an anchored section. Renders nothing when
 * the project has no report yet.
 */
export default function ProjectImpactSection({ report }: { report: ImpactSummary | null }) {
  if (!report) return null;
  const metrics = report.metrics ?? {};

  return (
    <section id="impact" aria-labelledby="impact-heading" className="mt-12 scroll-mt-24">
      <div className="bh-card p-8 md:p-10 text-center space-y-6">
        <div>
          <p className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary-red/10 text-primary-red text-xs font-bold uppercase tracking-widest border border-primary-red/20">
            <Award className="w-3 h-3" /> Official Impact Report
          </p>
          <h2 id="impact-heading" className="mt-4 text-2xl md:text-3xl font-black tracking-tight text-primary">
            Impact Score: {report.score}
          </h2>
          <p className="mt-2 text-sm text-secondary">
            Verified snapshot generated on {new Date(report.generated_at).toLocaleDateString()}
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-2xl mx-auto">
          <div className="rounded-xl border border-border bg-surface p-5">
            <TrendingUp className="w-5 h-5 mx-auto text-status-blue" />
            <p className="mt-2 text-2xl font-black text-primary">{metrics.views ?? 0}</p>
            <p className="text-[10px] font-mono uppercase tracking-widest text-secondary">Views</p>
          </div>
          <div className="rounded-xl border border-border bg-surface p-5">
            <Award className="w-5 h-5 mx-auto text-primary-red" />
            <p className="mt-2 text-2xl font-black text-primary">{metrics.likes ?? 0}</p>
            <p className="text-[10px] font-mono uppercase tracking-widest text-secondary">Likes</p>
          </div>
          <div className="rounded-xl border border-border bg-surface p-5">
            <Calendar className="w-5 h-5 mx-auto text-status-teal" />
            <p className="mt-2 text-2xl font-black text-primary">{metrics.comments ?? 0}</p>
            <p className="text-[10px] font-mono uppercase tracking-widest text-secondary">Comments</p>
          </div>
        </div>

        <p className="inline-flex items-center gap-2 text-xs text-secondary">
          <CheckCircle2 className="w-4 h-4 text-status-green" />
          Generated by the Butwal Hacks impact engine · Report {report.id.slice(0, 8)}
        </p>
      </div>
    </section>
  );
}
