/**
 * Festivals of BS 2081 — imported from the Hamro Patro-based community
 * feed (shresthasushil NepaliEvents.ics), major public observances only.
 * Routine vrats, sankrantis, shraddhas, saint jayantis, valley-only jatras
 * and international days are skipped by design.
 *
 * Regenerate with: node scripts/fetch-nepali-events.mjs [ics-path] --write
 *
 * Conventions match festivals-2083.ts. Human writeups (context lines)
 * are carried over across regenerations, matched by slug.
 */
import type { FestivalEntry } from "./festivals-2083";

export const FESTIVALS_2081: FestivalEntry[] = [
  {
    slug: "nepali-new-year-2081", group: "new-year",
    nameEn: "Nepali New Year", nameNe: "नयाँ वर्ष",
    tradition: "civic", bs: [2081, 1, 1], ad: [2024, 4, 13],
    contextEn: "First day of the year. New year, same you, fresh patro.",
    contextNe: "वर्षको पहिलो दिन। नयाँ वर्ष, नयाँ पात्रो।",
  },
  {
    slug: "chaite-dashain-2081", group: "chaite-dashain",
    nameEn: "Chaite Dashain", nameNe: "चैते दशैं",
    tradition: "hindu", bs: [2081, 1, 4], ad: [2024, 4, 16],
    contextEn: "Spring Dashain: a smaller, quieter tika day in Chaitra for goddess worship.",
    contextNe: "चैते दशैं: चैतमा देवी पूजाको सानो टीकाको दिन।",
  },
  {
    slug: "ram-nawami-2081", group: "ram-nawami",
    nameEn: "Ram Nawami", nameNe: "रामनवमी",
    tradition: "hindu", bs: [2081, 1, 5], ad: [2024, 4, 17],
    contextEn: "Birthday of Ram: fasting, Ramayana readings, and crowded temples.",
    contextNe: "रामको जन्मदिन: व्रत, रामायण पाठ, मन्दिरमा भीड।",
  },
  {
    slug: "loktantra-diwas-2081", group: "loktantra-diwas",
    nameEn: "Loktantra Diwas", nameNe: "लोकतन्त्र दिवस",
    tradition: "civic", bs: [2081, 1, 11], ad: [2024, 4, 23],
    contextEn: "Day democracy returned to the streets: marked since 2006.",
    contextNe: "प्रजातन्त्र सडकमा फर्केको दिन: २०६३ देखि मनाइने लोकतन्त्र दिवस।",
  },
  {
    slug: "mata-tirtha-aunsi-2081", group: "mata-tirtha-aunsi",
    nameEn: "Mata Tirtha Aunsi", nameNe: "मातातीर्थ औंसी",
    tradition: "hindu", bs: [2081, 1, 26], ad: [2024, 5, 8],
    contextEn: "Mother's day: the pond at Mata Tirtha fills with children honoring mothers, living and gone.",
    contextNe: "आमाको मुख हेर्ने दिन: मातातीर्थमा छोराछोरीको भीड।",
  },
  {
    slug: "buddha-jayanti-2081", group: "buddha-jayanti",
    nameEn: "Buddha Jayanti", nameNe: "बुद्ध जयन्ती",
    tradition: "buddhist", bs: [2081, 2, 10], ad: [2024, 5, 23],
    contextEn: "Birth, enlightenment, and passing of the Buddha, on one full-moon day.",
    contextNe: "बुद्धको जन्म, बोध र महापरिनिर्वाण एउटै पूर्णिमामा।",
  },
  {
    slug: "ubhauli-2081", group: "ubhauli",
    nameEn: "Ubhauli", nameNe: "उभौली",
    tradition: "janajati", bs: [2081, 2, 10], ad: [2024, 5, 23],
    contextEn: "Kiranti spring festival: the community moves uphill with the season, drums first.",
    contextNe: "किराँती वसन्त चाड: ढोलसँग उभौली यात्रा।",
  },
  {
    slug: "republic-day-2081", group: "prajatantra-diwas",
    nameEn: "Republic Day", nameNe: "गणतन्त्र दिवस",
    tradition: "civic", bs: [2081, 2, 15], ad: [2024, 5, 28],
    contextEn: "Nepal a republic: parades and programs for Ganatantra Day.",
    contextNe: "नेपाल गणतन्त्र: गणतन्त्र दिवसमा परेड र कार्यक्रम।",
  },
  {
    slug: "sithi-chahre-2081", group: "sithi-chahre",
    nameEn: "Sithi Chahre", nameNe: "सिथि चःह्रे",
    tradition: "janajati", bs: [2081, 2, 23], ad: [2024, 6, 5],
    contextEn: "Water sources cleaned, Kumar honored: the Newar festival of Sithi.",
    contextNe: "सिथि चःह्रे: पानीका मुहान सफा, कुमारको पूजा र भोज।",
  },
  {
    slug: "sithi-nakha-2081", group: "sithi-chahre",
    nameEn: "Sithi Nakha", nameNe: "सिथि नख:",
    tradition: "janajati", bs: [2081, 2, 30], ad: [2024, 6, 12],
    contextEn: "The great Newar Kumar festival: wells and ponds cleaned by whole toles.",
    contextNe: "सिथि नखः: इनार र पोखरी सफा गर्ने ठूलो नेवार चाड।",
  },
  {
    slug: "eid-al-adha-2081", group: "eid-adha",
    nameEn: "Eid al-Adha", nameNe: "ईद अल-अधा",
    tradition: "muslim", bs: [2081, 3, 3], ad: [2024, 6, 17],
    contextEn: "Festival of sacrifice: prayers, feasts, and giving to the poor.",
    contextNe: "बलिदानको चाड: नमाज, भोज र गरिबलाई दान।",
  },
  {
    slug: "bhumi-puja-2081", group: "bhumi-puja",
    nameEn: "Bhumi Puja", nameNe: "भूमि पूजा",
    tradition: "hindu", bs: [2081, 3, 11], ad: [2024, 6, 25],
    contextEn: "Worship of the earth before building or planting: the ground gets thanked first.",
    contextNe: "बनाउन वा रोप्नअघि भूमिको पूजा: पहिले माटोलाई धन्यवाद।",
  },
  {
    slug: "maghe-sankranti-2081-2", group: "maghe-sankranti",
    nameEn: "Maghe Sankranti", nameNe: "माघे संक्रान्ति",
    tradition: "hindu", bs: [2081, 3, 15], ad: [2024, 6, 29],
    contextEn: "Sun enters Capricorn; winter's back breaks. Tharu Maghi new year, til-laddu and yam day.",
    contextNe: "सूर्य मकरमा; जाडोको ढाड भाँचिन्छ। थारू नयाँ वर्ष, तिल-लड्डु र तरुलको दिन।",
  },
  {
    slug: "kheer-khane-din-2081", group: "kheer-khane",
    nameEn: "Kheer Khane Din", nameNe: "खीर खाने दिन",
    tradition: "hindu", bs: [2081, 4, 15], ad: [2024, 7, 30],
    contextEn: "Rice-pudding day on Shrawan 15: kheer in every Nepali kitchen.",
    contextNe: "साउन १५ मा खीर खाने दिन: हरेक भान्सामा खीर।",
  },
  {
    slug: "gathamuga-chahre-2081", group: "gathamuga",
    nameEn: "Gathamuga Chahre", nameNe: "गथांमुगः चःह्रे",
    tradition: "janajati", bs: [2081, 4, 18], ad: [2024, 8, 2],
    contextEn: "Newar festival chasing evil out: straw effigies burned at crossroads.",
    contextNe: "नेवार चाड: नराम्रोलाई खेद्न चोकमा पुत्ला जलाइन्छ।",
  },
  {
    slug: "tharu-guriya-2081", group: "tharu-guriya",
    nameEn: "Tharu Guriya", nameNe: "थारु गुरिया",
    tradition: "janajati", bs: [2081, 4, 25], ad: [2024, 8, 9],
    contextEn: "Tharu festival of Guriya Mai: the village goddess honored with offerings.",
    contextNe: "थारु गुरिया पर्व: गाउँकी देवीको पूजा र भोज।",
  },
  {
    slug: "nag-panchami-2081", group: "nag-panchami",
    nameEn: "Nag Panchami", nameNe: "नागपञ्चमी",
    tradition: "hindu", bs: [2081, 4, 25], ad: [2024, 8, 9],
    contextEn: "Snake-god day: Nag pictures pasted above doors against lightning and evil.",
    contextNe: "नागको दिन: चट्याङ र नराम्रोबाट बच्न ढोकामाथि नाग टाँसिन्छ।",
  },
  {
    slug: "raksha-bandhan-2081", group: "raksha-bandhan",
    nameEn: "Raksha Bandhan", nameNe: "रक्षाबन्धन",
    tradition: "hindu", bs: [2081, 5, 3], ad: [2024, 8, 19],
    contextEn: "Sacred thread day. Brothers and sisters tie protection on each other's wrists.",
    contextNe: "डोरो बाँध्ने दिन।",
  },
  {
    slug: "gaura-saptami-2081", group: "gaura",
    nameEn: "Gaura Saptami", nameNe: "गौरा सप्तमी",
    tradition: "janajati", bs: [2081, 5, 9], ad: [2024, 8, 25],
    contextEn: "Seventh day of Gaura: the festival peaks with fasting and song.",
    contextNe: "गौराको सातौं दिन: व्रत र गीतसँग चाड उत्कर्षमा।",
  },
  {
    slug: "gaura-festival-2081", group: "gaura",
    nameEn: "Gaura Festival", nameNe: "गौरा पर्व",
    tradition: "janajati", bs: [2081, 5, 10], ad: [2024, 8, 26],
    contextEn: "Far-western festival honoring Gauri: deuda dances for days.",
    contextNe: "सुदूरपश्चिमको चाड: देउडा नाचसँग गौरीको पूजा।",
  },
  {
    slug: "krishna-janmashtami-2081", group: "krishna-janmashtami",
    nameEn: "Krishna Janmashtami", nameNe: "कृष्ण जन्माष्टमी",
    tradition: "hindu", bs: [2081, 5, 10], ad: [2024, 8, 26],
    contextEn: "Midnight birth of Krishna. Fasts break after the night puja.",
    contextNe: "कृष्णको मध्यरात जन्म। राति पूजा पछि व्रत खोलिन्छ।",
  },
  {
    slug: "kushe-aunsi-2081", group: "kushe-aunsi",
    nameEn: "Kushe Aunsi", nameNe: "कुशे औंसी",
    tradition: "hindu", bs: [2081, 5, 17], ad: [2024, 9, 2],
    contextEn: "Father's day: kushe grass picked, fathers honored with sweets and gifts.",
    contextNe: "बुवाको मुख हेर्ने दिन: कुशे टिपिन्छ, बुवालाई मिठाइ र उपहार।",
  },
  {
    slug: "dar-khane-teej-eve-2081", group: "teej",
    nameEn: "Dar Khane (Teej Eve)", nameNe: "दर खाने दिन",
    tradition: "hindu", bs: [2081, 5, 20], ad: [2024, 9, 5],
    contextEn: "The night before Teej: women gather for the feast before the fast.",
    contextNe: "तीजको अघिल्लो रात: व्रतअघि भेला भएर दर खाने।",
  },
  {
    slug: "haritalika-teej-2081", group: "teej",
    nameEn: "Haritalika Teej", nameNe: "हरितालिका तीज",
    tradition: "hindu", bs: [2081, 5, 21], ad: [2024, 9, 6],
    contextEn: "Women fast and dance in red for marital bliss and Shiva-Parvati's union.",
    contextNe: "महिलाहरू रातोमा नाच्छन्, व्रत बस्छन्।",
  },
  {
    slug: "ganesh-chaturthi-2081", group: "ganesh-chaturthi",
    nameEn: "Ganesh Chaturthi", nameNe: "गणेश चतुर्थी",
    tradition: "hindu", bs: [2081, 5, 22], ad: [2024, 9, 7],
    contextEn: "Birthday of Ganesh, remover of obstacles: modaks and new beginnings.",
    contextNe: "विघ्नहर्ता गणेशको जन्मदिन: मोदक र नयाँ सुरुवात।",
  },
  {
    slug: "rishi-panchami-2081", group: "teej",
    nameEn: "Rishi Panchami", nameNe: "ऋषि पञ्चमी",
    tradition: "hindu", bs: [2081, 5, 23], ad: [2024, 9, 8],
    contextEn: "Day after Teej: ritual cleansing and homage to the seven sages.",
    contextNe: "तीजको भोलिपल्ट: शुद्धीकरण र सप्तऋषि पूजा।",
  },
  {
    slug: "chhath-parva-2081-2", group: "chhath",
    nameEn: "Chhath Parva", nameNe: "छठ पर्व",
    tradition: "hindu", bs: [2081, 5, 24], ad: [2024, 9, 9],
    contextEn: "Sun worship at riverbanks at dawn and dusk. The Terai's biggest festival.",
    contextNe: "नदी किनारमा सूर्य पूजा। तराईको ठूलो चाड।",
  },
  {
    slug: "ananta-chaturdashi-2081", group: "ananta-chaturdashi",
    nameEn: "Ananta Chaturdashi", nameNe: "अनन्त चतुर्दशी",
    tradition: "hindu", bs: [2081, 6, 1], ad: [2024, 9, 17],
    contextEn: "Fourteen knots for Vishnu: a thread tied on the wrist for year-long protection.",
    contextNe: "विष्णुका लागि चौध गाँठो: वर्षभरि रक्षाका लागि नाडीमा डोरो।",
  },
  {
    slug: "chepang-chonam-2081", group: "chepang-chonam",
    nameEn: "Chepang Chonam", nameNe: "चेपाङ चोनाम",
    tradition: "janajati", bs: [2081, 6, 2], ad: [2024, 9, 18],
    contextEn: "Chepang harvest festival: new grain honored with dance and feasting.",
    contextNe: "चेपाङ बाली चाड: नाच र भोजसँग नयाँ अन्नको सम्मान।",
  },
  {
    slug: "constitution-day-2081", group: "constitution-day",
    nameEn: "Constitution Day", nameNe: "संविधान दिवस",
    tradition: "civic", bs: [2081, 6, 3], ad: [2024, 9, 19],
    contextEn: "Nepal's constitution day. Parades, speeches, and a day off.",
    contextNe: "नेपालको संविधान दिवस। परेड, भाषण र बिदा।",
  },
  {
    slug: "jitiya-parva-2081", group: "jitiya",
    nameEn: "Jitiya Parva", nameNe: "जितिया पर्व",
    tradition: "janajati", bs: [2081, 6, 9], ad: [2024, 9, 25],
    contextEn: "Tharu and Madheshi mothers fast for their children's long life.",
    contextNe: "थारू र मधेसी आमाहरू सन्तानको दीर्घायुका लागि व्रत बस्छन्।",
  },
  {
    slug: "pitri-visarjan-2081", group: "pitri-paksha",
    nameEn: "Pitri Visarjan", nameNe: "पितृ विसर्जन",
    tradition: "hindu", bs: [2081, 6, 16], ad: [2024, 10, 2],
    contextEn: "Ancestors sent off: the last day of Sorha Shraddha, lamps floated downstream.",
    contextNe: "पितृ बिदा: सोह्र श्राद्धको अन्तिम दिन।",
  },
  {
    slug: "ghatasthapana-2081", group: "dashain",
    nameEn: "Ghatasthapana", nameNe: "घटस्थापना",
    tradition: "hindu", bs: [2081, 6, 17], ad: [2024, 10, 3],
    contextEn: "Day 1 of 15: barley seeds (jamara) are sown and the kalash installed. Dashain begins.",
    contextNe: "१५ दिने दशैंको दिन १: जमरा छरिन्छ, कलश स्थापना हुन्छ।",
  },
  {
    slug: "phulpati-2081", group: "dashain",
    nameEn: "Phulpati", nameNe: "फूलपाती",
    tradition: "hindu", bs: [2081, 6, 24], ad: [2024, 10, 10],
    contextEn: "Day 7: sacred flowers and jamara carried to Hanuman Dhoka in procession.",
    contextNe: "दिन ७: फूलपाती हनुमानढोका लगिन्छ।",
  },
  {
    slug: "maha-ashtami-2081", group: "dashain",
    nameEn: "Maha Ashtami", nameNe: "महा अष्टमी",
    tradition: "hindu", bs: [2081, 6, 25], ad: [2024, 10, 11],
    contextEn: "Day 8: Kaal Ratri, the fierce night of Durga worship.",
    contextNe: "दिन ८: कालरात्रि, दुर्गाको उग्र पूजा।",
  },
  {
    slug: "maha-navami-2081", group: "dashain",
    nameEn: "Maha Navami", nameNe: "महा नवमी",
    tradition: "hindu", bs: [2081, 6, 25], ad: [2024, 10, 11],
    contextEn: "Day 9: last night of Navaratri. Vehicles and tools get blessed too.",
    contextNe: "दिन ९: नवरात्रिको अन्तिम रात।",
  },
  {
    slug: "devi-visarjan-2081", group: "dashain",
    nameEn: "Devi Visarjan", nameNe: "देवी विसर्जन",
    tradition: "hindu", bs: [2081, 6, 26], ad: [2024, 10, 12],
    contextEn: "The goddess goes home: Dashain idols are immersed, closing the festival.",
    contextNe: "देवी बिदा: दशैंका मूर्ति सेलाइन्छन्, चाड सकिन्छ।",
  },
  {
    slug: "vijaya-dashami-2081", group: "dashain",
    nameEn: "Vijaya Dashami", nameNe: "विजया दशमी",
    tradition: "hindu", bs: [2081, 6, 26], ad: [2024, 10, 12],
    contextEn: "Day 10, the heart of Dashain: elders place tika and jamara.",
    contextNe: "दिन १०, दशैंको मुटु: ठूलाले टीका-जमरा लगाइदिन्छन्।",
  },
  {
    slug: "dhanteras-2081", group: "tihar",
    nameEn: "Dhanteras", nameNe: "धनतेरस",
    tradition: "hindu", bs: [2081, 7, 13], ad: [2024, 10, 29],
    contextEn: "Day of wealth before Tihar: metal and new utensils bought for luck.",
    contextNe: "तिहारअघि धनको दिन: शुभका लागि धातु र भाँडा किनिन्छ।",
  },
  {
    slug: "kag-tihar-2081", group: "tihar",
    nameEn: "Kag Tihar", nameNe: "काग तिहार",
    tradition: "hindu", bs: [2081, 7, 14], ad: [2024, 10, 30],
    contextEn: "Day 1 of 5: crows, messengers of Yama, get the first food.",
    contextNe: "५ दिने तिहारको दिन १: कागलाई पहिलो खाना।",
  },
  {
    slug: "kukur-tihar-2081", group: "tihar",
    nameEn: "Kukur Tihar", nameNe: "कुकुर तिहार",
    tradition: "hindu", bs: [2081, 7, 15], ad: [2024, 10, 31],
    contextEn: "Day 2: dogs garlanded and feasted, street dogs included.",
    contextNe: "दिन २: कुकुरलाई माला र भोज।",
  },
  {
    slug: "laxmi-puja-2081", group: "tihar",
    nameEn: "Laxmi Puja", nameNe: "लक्ष्मी पूजा",
    tradition: "hindu", bs: [2081, 7, 15], ad: [2024, 10, 31],
    contextEn: "Night of lights: homes glow with oil lamps for the goddess of wealth.",
    contextNe: "बत्तीको रात: लक्ष्मीका लागि दियो।",
  },
  {
    slug: "narak-chaturdashi-2081", group: "tihar",
    nameEn: "Narak Chaturdashi", nameNe: "नरक चतुर्दशी",
    tradition: "hindu", bs: [2081, 7, 15], ad: [2024, 10, 31],
    contextEn: "Hell's-eve: lamps lit to guide ancestors and scare off bad spirits.",
    contextNe: "नरक चतुर्दशी: पितृका लागि र नराम्रो धपाउन बत्ती।",
  },
  {
    slug: "mha-puja-2081", group: "tihar",
    nameEn: "Mha Puja", nameNe: "म्ह पूजा",
    tradition: "janajati", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "Newar worship of the self: the body honored as the year's true temple.",
    contextNe: "आफ्नै पूजा: शरीरलाई वर्षको साँचो मन्दिर मानिन्छ।",
  },
  {
    slug: "hali-tihar-2081", group: "tihar",
    nameEn: "Hali Tihar", nameNe: "हलि तिहार",
    tradition: "hindu", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "Ploughmen's day in Tihar: the halis who till the fields are feasted.",
    contextNe: "तिहारमा हलिको दिन: खेत जोत्नेलाई भोज।",
  },
  {
    slug: "gobardhan-puja-2081", group: "tihar",
    nameEn: "Gobardhan Puja", nameNe: "गोवर्धन पूजा",
    tradition: "hindu", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "Govardhan hill worship: Krishna's mountain-lifting remembered with cow-dung mounds.",
    contextNe: "गोवर्धन पूजा: कृष्णको पर्वत उचाइ सम्झिँदै गोबरको थुप्रो।",
  },
  {
    slug: "nepal-sambat-new-year-2081", group: "nepal-sambat",
    nameEn: "Nepal Sambat New Year", nameNe: "नेपाल संवत् नयाँ वर्ष",
    tradition: "janajati", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "Newar new year: Mha Puja morning, fresh ledgers, Bhai Dooj evening.",
    contextNe: "नेवार नयाँ वर्ष: बिहान म्ह पूजा, नयाँ हिसाब।",
  },
  {
    slug: "gai-tihar-2081", group: "tihar",
    nameEn: "Gai Tihar", nameNe: "गाई तिहार",
    tradition: "hindu", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "Cows honored with garlands and treats: wealth on four legs.",
    contextNe: "गाईलाई माला र खानेकुरा: चार खुट्टे धनको सम्मान।",
  },
  {
    slug: "kija-puja-2081", group: "tihar",
    nameEn: "Kija Puja", nameNe: "किजा पूजा",
    tradition: "janajati", bs: [2081, 7, 18], ad: [2024, 11, 3],
    contextEn: "Newar Bhai Tika: sisters honor brothers with egg, fish, and wine.",
    contextNe: "नेवार भाइटीका: दिदीबहिनीले दाजुभाइलाई अन्डा-माछासहित पूजा।",
  },
  {
    slug: "bhai-tika-2081", group: "tihar",
    nameEn: "Bhai Tika", nameNe: "भाइ टीका",
    tradition: "hindu", bs: [2081, 7, 18], ad: [2024, 11, 3],
    contextEn: "Day 5, the finale: sisters place seven-color tika on brothers for protection and long life.",
    contextNe: "दिन ५, समापन: दिदीबहिनीले दाजुभाइलाई सप्तरंगी टीका।",
  },
  {
    slug: "chhath-parva-2081", group: "chhath",
    nameEn: "Chhath Parva", nameNe: "छठ पर्व",
    tradition: "hindu", bs: [2081, 7, 22], ad: [2024, 11, 7],
    contextEn: "Sun worship at riverbanks at dawn and dusk. The Terai's biggest festival.",
    contextNe: "नदी किनारमा सूर्य पूजा। तराईको ठूलो चाड।",
  },
  {
    slug: "gopashtami-2081", group: "gopashtami",
    nameEn: "Gopashtami", nameNe: "गोपाष्टमी",
    tradition: "hindu", bs: [2081, 7, 24], ad: [2024, 11, 9],
    contextEn: "Cowherd day: cows decorated and worshipped, calves fed first.",
    contextNe: "गोठालो दिन: गाई सिँगारिन्छ, पूजा हुन्छ।",
  },
  {
    slug: "bala-chaturdashi-2081", group: "bala-chaturdashi",
    nameEn: "Bala Chaturdashi", nameNe: "बाला चतुर्दशी",
    tradition: "hindu", bs: [2081, 8, 15], ad: [2024, 11, 30],
    contextEn: "A night of lamps for the departed: Pashupatinath glows with oil lights.",
    contextNe: "पितृका लागि बत्तीको रात: पशुपतिनाथ दियोले उज्यालो।",
  },
  {
    slug: "gadhimai-mela-2081", group: "gadhimai",
    nameEn: "Gadhimai Mela", nameNe: "गढीमाई मेला",
    tradition: "hindu", bs: [2081, 8, 17], ad: [2024, 12, 2],
    contextEn: "The great five-yearly fair at Gadhimai temple in Bara, honoring the goddess.",
    contextNe: "बाराको गढीमाईमा पाँच वर्षे ठूलो मेला।",
  },
  {
    slug: "vivah-panchami-2081", group: "vivah-panchami",
    nameEn: "Vivah Panchami", nameNe: "विवाह पञ्चमी",
    tradition: "hindu", bs: [2081, 8, 21], ad: [2024, 12, 6],
    contextEn: "Wedding of Ram and Sita: Janakpur celebrates like family.",
    contextNe: "राम-सीता विवाह: जनकपुरमा घरकै बिहे जस्तो।",
  },
  {
    slug: "gita-jayanti-2081", group: "gita-jayanti",
    nameEn: "Gita Jayanti", nameNe: "गीता जयन्ती",
    tradition: "hindu", bs: [2081, 8, 26], ad: [2024, 12, 11],
    contextEn: "Day the Gita was spoken: readings and recitations of Krishna's counsel.",
    contextNe: "गीता सुनाइएको दिन: कृष्णको उपदेश पाठ र वाचन।",
  },
  {
    slug: "dhanya-purnima-2081", group: "udhauli",
    nameEn: "Dhanya Purnima", nameNe: "धान्य पूर्णिमा",
    tradition: "janajati", bs: [2081, 8, 30], ad: [2024, 12, 15],
    contextEn: "Harvest full moon: Kiranti Udhauli and Newar Yomari Punhi share the day.",
    contextNe: "बाली पूर्णिमा: उधौली र यःमरि पुन्हि एकै दिन।",
  },
  {
    slug: "udhauli-2081", group: "udhauli",
    nameEn: "Udhauli", nameNe: "उधौली",
    tradition: "janajati", bs: [2081, 8, 30], ad: [2024, 12, 15],
    contextEn: "Kiranti harvest festival: the migration downhill, dances and millet beer.",
    contextNe: "किराँती बाली चाड: उधौली नाच र जाँडसँग।",
  },
  {
    slug: "jyapu-day-2081", group: "udhauli",
    nameEn: "Jyapu Day", nameNe: "ज्यापू दिवस",
    tradition: "janajati", bs: [2081, 8, 30], ad: [2024, 12, 15],
    contextEn: "Newar farmer day: the Jyapu community honored with yomari and feasts.",
    contextNe: "ज्यापू दिवस: किसान समुदायको सम्मान, यःमरि र भोजसँग।",
  },
  {
    slug: "christmas-day-2081", group: "christmas",
    nameEn: "Christmas Day", nameNe: "क्रिसमस डे",
    tradition: "christian", bs: [2081, 9, 10], ad: [2024, 12, 25],
    contextEn: "Public holiday for Christians in Nepal.",
    contextNe: "नेपालका क्रिस्चियनका लागि सार्वजनिक बिदा।",
  },
  {
    slug: "tamu-lhosar-2081", group: "tamu-lhosar",
    nameEn: "Tamu Lhosar", nameNe: "तमु ल्होसार",
    tradition: "janajati", bs: [2081, 9, 15], ad: [2024, 12, 30],
    contextEn: "Gurung new year: feasts, dances, and homecomings in the hills.",
    contextNe: "गुरुङ नयाँ वर्ष।",
  },
  {
    slug: "tol-lhosar-2081", group: "tol-lhosar",
    nameEn: "Tol Lhosar", nameNe: "तोल ल्होसार",
    tradition: "janajati", bs: [2081, 9, 16], ad: [2024, 12, 31],
    contextEn: "New year of the highland Tol Tamangs: feasts and dances.",
    contextNe: "तोल तामाङ नयाँ वर्ष: लेकमा भोज र नाच।",
  },
  {
    slug: "topi-diwas-2081", group: "topi-diwas",
    nameEn: "Topi Diwas", nameNe: "टोपी दिवस",
    tradition: "civic", bs: [2081, 9, 17], ad: [2025, 1, 1],
    contextEn: "Topi day on Gregorian New Year: Dhaka topis out, selfies in.",
    contextNe: "अङ्ग्रेजी नयाँ वर्षमा टोपी दिवस: ढाका टोपी लगाउने दिन।",
  },
  {
    slug: "nepali-new-year-2081-2", group: "new-year",
    nameEn: "Nepali New Year", nameNe: "नयाँ वर्ष",
    tradition: "civic", bs: [2081, 9, 17], ad: [2025, 1, 1],
    contextEn: "First day of the year. New year, same you, fresh patro.",
    contextNe: "वर्षको पहिलो दिन। नयाँ वर्ष, नयाँ पात्रो।",
  },
  {
    slug: "prithvi-jayanti-2081", group: "prithvi-jayanti",
    nameEn: "Prithvi Jayanti", nameNe: "पृथ्वी जयन्ती",
    tradition: "civic", bs: [2081, 9, 27], ad: [2025, 1, 11],
    contextEn: "Birthday of Prithvi Narayan Shah, unifier of Nepal.",
    contextNe: "नेपाल एकीकरणकर्ता पृथ्वीनारायण शाहको जन्मदिन।",
  },
  {
    slug: "maghe-sankranti-2081", group: "maghe-sankranti",
    nameEn: "Maghe Sankranti", nameNe: "माघे संक्रान्ति",
    tradition: "hindu", bs: [2081, 10, 1], ad: [2025, 1, 14],
    contextEn: "Sun enters Capricorn; winter's back breaks. Tharu Maghi new year, til-laddu and yam day.",
    contextNe: "सूर्य मकरमा; जाडोको ढाड भाँचिन्छ। थारू नयाँ वर्ष, तिल-लड्डु र तरुलको दिन।",
  },
  {
    slug: "martyrs-day-2081", group: "martyrs-day",
    nameEn: "Martyrs' Day", nameNe: "शहीद दिवस",
    tradition: "civic", bs: [2081, 10, 16], ad: [2025, 1, 29],
    contextEn: "For the four martyrs. Quiet wreaths at Shaheed Gate.",
    contextNe: "चार शहीदका लागि। शहीद गेटमा मौन माल्यार्पण।",
  },
  {
    slug: "sonam-lhosar-2081", group: "sonam-lhosar",
    nameEn: "Sonam Lhosar", nameNe: "सोनाम ल्होसार",
    tradition: "buddhist", bs: [2081, 10, 17], ad: [2025, 1, 30],
    contextEn: "Tamang new year: dumplings, dances, monastery crowds.",
    contextNe: "तामाङ नयाँ वर्ष।",
  },
  {
    slug: "saraswati-puja-2081", group: "saraswati-puja",
    nameEn: "Saraswati Puja", nameNe: "सरस्वती पूजा",
    tradition: "hindu", bs: [2081, 10, 21], ad: [2025, 2, 3],
    contextEn: "Goddess of learning day: children write first letters, books get tika.",
    contextNe: "सरस्वती पूजा: नानीहरू पहिलो अक्षर लेख्छन्, किताबमा टीका।",
  },
  {
    slug: "skanda-shashti-2081", group: "skanda-shashti",
    nameEn: "Skanda Shashti", nameNe: "स्कन्द षष्ठी",
    tradition: "hindu", bs: [2081, 10, 22], ad: [2025, 2, 4],
    contextEn: "Sixth day for Skanda (Kumar): fasting for sons and soldiers.",
    contextNe: "स्कन्द षष्ठी: कुमारका लागि व्रत।",
  },
  {
    slug: "prajatantra-diwas-2081", group: "prajatantra-diwas",
    nameEn: "Prajatantra Diwas", nameNe: "प्रजातन्त्र दिवस",
    tradition: "civic", bs: [2081, 11, 7], ad: [2025, 2, 19],
    contextEn: "Fall of the Ranas, dawn of democracy. Parades at Tundikhel.",
    contextNe: "राणा शासनको अन्त्य, प्रजातन्त्रको बिहान।",
  },
  {
    slug: "army-day-2081", group: "army-day",
    nameEn: "Army Day", nameNe: "सेना दिवस",
    tradition: "civic", bs: [2081, 11, 14], ad: [2025, 2, 26],
    contextEn: "Parades on Shivaratri day: the army opens its gates at Tundikhel.",
    contextNe: "शिवरात्रिकै दिन परेड: टुँडिखेलमा सेनाको ढोका खुल्छ।",
  },
  {
    slug: "maha-shivaratri-2081", group: "maha-shivaratri",
    nameEn: "Maha Shivaratri", nameNe: "महा शिवरात्रि",
    tradition: "hindu", bs: [2081, 11, 14], ad: [2025, 2, 26],
    contextEn: "The great night of Shiva: fasting, vigils, and packed Pashupatinath.",
    contextNe: "शिवको महान रात: व्रत, जाग्राम, पशुपतिनाथमा भीड।",
  },
  {
    slug: "gyalpo-lhosar-2081", group: "gyalpo-lhosar",
    nameEn: "Gyalpo Lhosar", nameNe: "ग्याल्पो ल्होसार",
    tradition: "buddhist", bs: [2081, 11, 16], ad: [2025, 2, 28],
    contextEn: "Sherpa and high-Himalayan new year. Khada scarves and chang toasts.",
    contextNe: "शेर्पा नयाँ वर्ष। खदा र छ्याङ।",
  },
  {
    slug: "women-s-day-2081", group: "womens-day",
    nameEn: "Women's Day", nameNe: "नारी दिवस",
    tradition: "civic", bs: [2081, 11, 24], ad: [2025, 3, 8],
    contextEn: "Rallies and programs nationwide; public holiday for women.",
    contextNe: "देशभर र्‍याली; महिलाका लागि सार्वजनिक बिदा।",
  },
  {
    slug: "holi-hills-2081", group: "holi",
    nameEn: "Holi (Hills)", nameNe: "होली (पहाड)",
    tradition: "hindu", bs: [2081, 11, 29], ad: [2025, 3, 13],
    contextEn: "Colors in the hills a day before the Terai. Abir, water, strangers turned friends.",
    contextNe: "तराईभन्दा एक दिन अघि पहाडमा रङ।",
  },
  {
    slug: "holi-terai-2081", group: "holi",
    nameEn: "Holi (Terai)", nameNe: "होली (तराई)",
    tradition: "hindu", bs: [2081, 12, 1], ad: [2025, 3, 14],
    contextEn: "Terai plays Holi a day later, on Fagu Purnima proper.",
    contextNe: "तराईमा एक दिन पछि, फागु पूर्णिमामै होली।",
  },
  {
    slug: "gangaur-puja-2081", group: "gangaur",
    nameEn: "Gangaur Puja", nameNe: "गणगौर पूजा",
    tradition: "hindu", bs: [2081, 12, 2], ad: [2025, 3, 15],
    contextEn: "Tharu and Madheshi women honor Gauri for marital bliss and good harvests.",
    contextNe: "थारू र मधेसी महिलाले गौरीको पूजा: सुखी जीवन र बालीका लागि।",
  },
  {
    slug: "pahan-chahre-2081", group: "pahan-chahre",
    nameEn: "Pahan Chahre", nameNe: "पाहाँचःह्रे",
    tradition: "janajati", bs: [2081, 12, 15], ad: [2025, 3, 28],
    contextEn: "Newar festival of Pahan: the deity paraded through old Kathmandu.",
    contextNe: "पाहाँ चःह्रे: पुरानो काठमाडौंमा देवताको जात्रा।",
  },
  {
    slug: "eid-al-fitr-2081", group: "eid-fitr",
    nameEn: "Eid al-Fitr", nameNe: "ईद अल-फित्र",
    tradition: "muslim", bs: [2081, 12, 18], ad: [2025, 3, 31],
    contextEn: "End of Ramadan: morning prayers, sweet sevai, and embraces all around.",
    contextNe: "रमजानको अन्त्य: बिहानी नमाज, मिठो सेवई, अँगालो।",
  },
  {
    slug: "chaite-dashain-2081-2", group: "chaite-dashain",
    nameEn: "Chaite Dashain", nameNe: "चैते दशैं",
    tradition: "hindu", bs: [2081, 12, 23], ad: [2025, 4, 5],
    contextEn: "Spring Dashain: a smaller, quieter tika day in Chaitra for goddess worship.",
    contextNe: "चैते दशैं: चैतमा देवी पूजाको सानो टीकाको दिन।",
  },
  {
    slug: "ram-nawami-2081-2", group: "ram-nawami",
    nameEn: "Ram Nawami", nameNe: "रामनवमी",
    tradition: "hindu", bs: [2081, 12, 24], ad: [2025, 4, 6],
    contextEn: "Birthday of Ram: fasting, Ramayana readings, and crowded temples.",
    contextNe: "रामको जन्मदिन: व्रत, रामायण पाठ, मन्दिरमा भीड।",
  },
];
