/**
 * Festivals of BS 2081 — imported from the Hamro Patro-based community
 * feed (shresthasushil NepaliEvents.ics), major public observances only.
 * Routine vrats, sankrantis, shraddhas, saint jayantis, valley-only jatras
 * and international days are skipped by design.
 *
 * Regenerate with: node scripts/fetch-nepali-events.mjs [ics-path] --write
 *
 * Conventions match festivals-2083.ts, except context lines are empty:
 * one-line writeups stay human-written per year. The Samiti file owns 2083;
 * this importer never emits 2083 rows.
 */
import type { FestivalEntry } from "./festivals-2083";

export const FESTIVALS_2081: FestivalEntry[] = [
  {
    slug: "nepali-new-year-2081", group: "new-year",
    nameEn: "Nepali New Year", nameNe: "नयाँ वर्ष",
    tradition: "civic", bs: [2081, 1, 1], ad: [2024, 4, 13],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chaite-dashain-2081", group: "chaite-dashain",
    nameEn: "Chaite Dashain", nameNe: "चैते दशैं",
    tradition: "hindu", bs: [2081, 1, 4], ad: [2024, 4, 16],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ram-nawami-2081", group: "ram-nawami",
    nameEn: "Ram Nawami", nameNe: "रामनवमी",
    tradition: "hindu", bs: [2081, 1, 5], ad: [2024, 4, 17],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "loktantra-diwas-2081", group: "loktantra-diwas",
    nameEn: "Loktantra Diwas", nameNe: "लोकतन्त्र दिवस",
    tradition: "civic", bs: [2081, 1, 11], ad: [2024, 4, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "mata-tirtha-aunsi-2081", group: "mata-tirtha-aunsi",
    nameEn: "Mata Tirtha Aunsi", nameNe: "मातातीर्थ औंसी",
    tradition: "hindu", bs: [2081, 1, 26], ad: [2024, 5, 8],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "buddha-jayanti-2081", group: "buddha-jayanti",
    nameEn: "Buddha Jayanti", nameNe: "बुद्ध जयन्ती",
    tradition: "buddhist", bs: [2081, 2, 10], ad: [2024, 5, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ubhauli-2081", group: "ubhauli",
    nameEn: "Ubhauli", nameNe: "उभौली",
    tradition: "janajati", bs: [2081, 2, 10], ad: [2024, 5, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "republic-day-2081", group: "prajatantra-diwas",
    nameEn: "Republic Day", nameNe: "गणतन्त्र दिवस",
    tradition: "civic", bs: [2081, 2, 15], ad: [2024, 5, 28],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "sithi-chahre-2081", group: "sithi-chahre",
    nameEn: "Sithi Chahre", nameNe: "सिथि चःह्रे",
    tradition: "janajati", bs: [2081, 2, 23], ad: [2024, 6, 5],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "sithi-nakha-2081", group: "sithi-chahre",
    nameEn: "Sithi Nakha", nameNe: "सिथि नख:",
    tradition: "janajati", bs: [2081, 2, 30], ad: [2024, 6, 12],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "eid-al-adha-2081", group: "eid-adha",
    nameEn: "Eid al-Adha", nameNe: "ईद अल-अधा",
    tradition: "muslim", bs: [2081, 3, 3], ad: [2024, 6, 17],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "bhumi-puja-2081", group: "bhumi-puja",
    nameEn: "Bhumi Puja", nameNe: "भूमि पूजा",
    tradition: "hindu", bs: [2081, 3, 11], ad: [2024, 6, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maghe-sankranti-2081-2", group: "maghe-sankranti",
    nameEn: "Maghe Sankranti", nameNe: "माघे संक्रान्ति",
    tradition: "hindu", bs: [2081, 3, 15], ad: [2024, 6, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kheer-khane-din-2081", group: "kheer-khane",
    nameEn: "Kheer Khane Din", nameNe: "खीर खाने दिन",
    tradition: "hindu", bs: [2081, 4, 15], ad: [2024, 7, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gathamuga-chahre-2081", group: "gathamuga",
    nameEn: "Gathamuga Chahre", nameNe: "गथांमुगः चःह्रे",
    tradition: "janajati", bs: [2081, 4, 18], ad: [2024, 8, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "tharu-guriya-2081", group: "tharu-guriya",
    nameEn: "Tharu Guriya", nameNe: "थारु गुरिया",
    tradition: "janajati", bs: [2081, 4, 25], ad: [2024, 8, 9],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "nag-panchami-2081", group: "nag-panchami",
    nameEn: "Nag Panchami", nameNe: "नागपञ्चमी",
    tradition: "hindu", bs: [2081, 4, 25], ad: [2024, 8, 9],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "raksha-bandhan-2081", group: "raksha-bandhan",
    nameEn: "Raksha Bandhan", nameNe: "रक्षाबन्धन",
    tradition: "hindu", bs: [2081, 5, 3], ad: [2024, 8, 19],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gaura-saptami-2081", group: "gaura",
    nameEn: "Gaura Saptami", nameNe: "गौरा सप्तमी",
    tradition: "janajati", bs: [2081, 5, 9], ad: [2024, 8, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gaura-festival-2081", group: "gaura",
    nameEn: "Gaura Festival", nameNe: "गौरा पर्व",
    tradition: "janajati", bs: [2081, 5, 10], ad: [2024, 8, 26],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "krishna-janmashtami-2081", group: "krishna-janmashtami",
    nameEn: "Krishna Janmashtami", nameNe: "कृष्ण जन्माष्टमी",
    tradition: "hindu", bs: [2081, 5, 10], ad: [2024, 8, 26],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kushe-aunsi-2081", group: "kushe-aunsi",
    nameEn: "Kushe Aunsi", nameNe: "कुशे औंसी",
    tradition: "hindu", bs: [2081, 5, 17], ad: [2024, 9, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "dar-khane-teej-eve-2081", group: "teej",
    nameEn: "Dar Khane (Teej Eve)", nameNe: "दर खाने दिन",
    tradition: "hindu", bs: [2081, 5, 20], ad: [2024, 9, 5],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "haritalika-teej-2081", group: "teej",
    nameEn: "Haritalika Teej", nameNe: "हरितालिका तीज",
    tradition: "hindu", bs: [2081, 5, 21], ad: [2024, 9, 6],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ganesh-chaturthi-2081", group: "ganesh-chaturthi",
    nameEn: "Ganesh Chaturthi", nameNe: "गणेश चतुर्थी",
    tradition: "hindu", bs: [2081, 5, 22], ad: [2024, 9, 7],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "rishi-panchami-2081", group: "teej",
    nameEn: "Rishi Panchami", nameNe: "ऋषि पञ्चमी",
    tradition: "hindu", bs: [2081, 5, 23], ad: [2024, 9, 8],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chhath-parva-2081-2", group: "chhath",
    nameEn: "Chhath Parva", nameNe: "छठ पर्व",
    tradition: "hindu", bs: [2081, 5, 24], ad: [2024, 9, 9],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ananta-chaturdashi-2081", group: "ananta-chaturdashi",
    nameEn: "Ananta Chaturdashi", nameNe: "अनन्त चतुर्दशी",
    tradition: "hindu", bs: [2081, 6, 1], ad: [2024, 9, 17],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chepang-chonam-2081", group: "chepang-chonam",
    nameEn: "Chepang Chonam", nameNe: "चेपाङ चोनाम",
    tradition: "janajati", bs: [2081, 6, 2], ad: [2024, 9, 18],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "constitution-day-2081", group: "constitution-day",
    nameEn: "Constitution Day", nameNe: "संविधान दिवस",
    tradition: "civic", bs: [2081, 6, 3], ad: [2024, 9, 19],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "jitiya-parva-2081", group: "jitiya",
    nameEn: "Jitiya Parva", nameNe: "जितिया पर्व",
    tradition: "janajati", bs: [2081, 6, 9], ad: [2024, 9, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "pitri-visarjan-2081", group: "pitri-paksha",
    nameEn: "Pitri Visarjan", nameNe: "पितृ विसर्जन",
    tradition: "hindu", bs: [2081, 6, 16], ad: [2024, 10, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ghatasthapana-2081", group: "dashain",
    nameEn: "Ghatasthapana", nameNe: "घटस्थापना",
    tradition: "hindu", bs: [2081, 6, 17], ad: [2024, 10, 3],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "phulpati-2081", group: "dashain",
    nameEn: "Phulpati", nameNe: "फूलपाती",
    tradition: "hindu", bs: [2081, 6, 24], ad: [2024, 10, 10],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maha-ashtami-2081", group: "dashain",
    nameEn: "Maha Ashtami", nameNe: "महा अष्टमी",
    tradition: "hindu", bs: [2081, 6, 25], ad: [2024, 10, 11],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maha-navami-2081", group: "dashain",
    nameEn: "Maha Navami", nameNe: "महा नवमी",
    tradition: "hindu", bs: [2081, 6, 25], ad: [2024, 10, 11],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "devi-visarjan-2081", group: "dashain",
    nameEn: "Devi Visarjan", nameNe: "देवी विसर्जन",
    tradition: "hindu", bs: [2081, 6, 26], ad: [2024, 10, 12],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "vijaya-dashami-2081", group: "dashain",
    nameEn: "Vijaya Dashami", nameNe: "विजया दशमी",
    tradition: "hindu", bs: [2081, 6, 26], ad: [2024, 10, 12],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "dhanteras-2081", group: "tihar",
    nameEn: "Dhanteras", nameNe: "धनतेरस",
    tradition: "hindu", bs: [2081, 7, 13], ad: [2024, 10, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kag-tihar-2081", group: "tihar",
    nameEn: "Kag Tihar", nameNe: "काग तिहार",
    tradition: "hindu", bs: [2081, 7, 14], ad: [2024, 10, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kukur-tihar-2081", group: "tihar",
    nameEn: "Kukur Tihar", nameNe: "कुकुर तिहार",
    tradition: "hindu", bs: [2081, 7, 15], ad: [2024, 10, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "laxmi-puja-2081", group: "tihar",
    nameEn: "Laxmi Puja", nameNe: "लक्ष्मी पूजा",
    tradition: "hindu", bs: [2081, 7, 15], ad: [2024, 10, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "narak-chaturdashi-2081", group: "tihar",
    nameEn: "Narak Chaturdashi", nameNe: "नरक चतुर्दशी",
    tradition: "hindu", bs: [2081, 7, 15], ad: [2024, 10, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "mha-puja-2081", group: "tihar",
    nameEn: "Mha Puja", nameNe: "म्ह पूजा",
    tradition: "janajati", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "hali-tihar-2081", group: "tihar",
    nameEn: "Hali Tihar", nameNe: "हलि तिहार",
    tradition: "hindu", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gobardhan-puja-2081", group: "tihar",
    nameEn: "Gobardhan Puja", nameNe: "गोवर्धन पूजा",
    tradition: "hindu", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "nepal-sambat-new-year-2081", group: "nepal-sambat",
    nameEn: "Nepal Sambat New Year", nameNe: "नेपाल संवत् नयाँ वर्ष",
    tradition: "janajati", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gai-tihar-2081", group: "tihar",
    nameEn: "Gai Tihar", nameNe: "गाई तिहार",
    tradition: "hindu", bs: [2081, 7, 17], ad: [2024, 11, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kija-puja-2081", group: "tihar",
    nameEn: "Kija Puja", nameNe: "किजा पूजा",
    tradition: "janajati", bs: [2081, 7, 18], ad: [2024, 11, 3],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "bhai-tika-2081", group: "tihar",
    nameEn: "Bhai Tika", nameNe: "भाइ टीका",
    tradition: "hindu", bs: [2081, 7, 18], ad: [2024, 11, 3],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chhath-parva-2081", group: "chhath",
    nameEn: "Chhath Parva", nameNe: "छठ पर्व",
    tradition: "hindu", bs: [2081, 7, 22], ad: [2024, 11, 7],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gopashtami-2081", group: "gopashtami",
    nameEn: "Gopashtami", nameNe: "गोपाष्टमी",
    tradition: "hindu", bs: [2081, 7, 24], ad: [2024, 11, 9],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "bala-chaturdashi-2081", group: "bala-chaturdashi",
    nameEn: "Bala Chaturdashi", nameNe: "बाला चतुर्दशी",
    tradition: "hindu", bs: [2081, 8, 15], ad: [2024, 11, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gadhimai-mela-2081", group: "gadhimai",
    nameEn: "Gadhimai Mela", nameNe: "गढीमाई मेला",
    tradition: "hindu", bs: [2081, 8, 17], ad: [2024, 12, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "vivah-panchami-2081", group: "vivah-panchami",
    nameEn: "Vivah Panchami", nameNe: "विवाह पञ्चमी",
    tradition: "hindu", bs: [2081, 8, 21], ad: [2024, 12, 6],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gita-jayanti-2081", group: "gita-jayanti",
    nameEn: "Gita Jayanti", nameNe: "गीता जयन्ती",
    tradition: "hindu", bs: [2081, 8, 26], ad: [2024, 12, 11],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "dhanya-purnima-2081", group: "udhauli",
    nameEn: "Dhanya Purnima", nameNe: "धान्य पूर्णिमा",
    tradition: "janajati", bs: [2081, 8, 30], ad: [2024, 12, 15],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "udhauli-2081", group: "udhauli",
    nameEn: "Udhauli", nameNe: "उधौली",
    tradition: "janajati", bs: [2081, 8, 30], ad: [2024, 12, 15],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "jyapu-day-2081", group: "udhauli",
    nameEn: "Jyapu Day", nameNe: "ज्यापू दिवस",
    tradition: "janajati", bs: [2081, 8, 30], ad: [2024, 12, 15],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "christmas-day-2081", group: "christmas",
    nameEn: "Christmas Day", nameNe: "क्रिसमस डे",
    tradition: "christian", bs: [2081, 9, 10], ad: [2024, 12, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "tamu-lhosar-2081", group: "tamu-lhosar",
    nameEn: "Tamu Lhosar", nameNe: "तमु ल्होसार",
    tradition: "janajati", bs: [2081, 9, 15], ad: [2024, 12, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "tol-lhosar-2081", group: "tol-lhosar",
    nameEn: "Tol Lhosar", nameNe: "तोल ल्होसार",
    tradition: "janajati", bs: [2081, 9, 16], ad: [2024, 12, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "topi-diwas-2081", group: "topi-diwas",
    nameEn: "Topi Diwas", nameNe: "टोपी दिवस",
    tradition: "civic", bs: [2081, 9, 17], ad: [2025, 1, 1],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "nepali-new-year-2081-2", group: "new-year",
    nameEn: "Nepali New Year", nameNe: "नयाँ वर्ष",
    tradition: "civic", bs: [2081, 9, 17], ad: [2025, 1, 1],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "prithvi-jayanti-2081", group: "prithvi-jayanti",
    nameEn: "Prithvi Jayanti", nameNe: "पृथ्वी जयन्ती",
    tradition: "civic", bs: [2081, 9, 27], ad: [2025, 1, 11],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maghe-sankranti-2081", group: "maghe-sankranti",
    nameEn: "Maghe Sankranti", nameNe: "माघे संक्रान्ति",
    tradition: "hindu", bs: [2081, 10, 1], ad: [2025, 1, 14],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "martyrs-day-2081", group: "martyrs-day",
    nameEn: "Martyrs' Day", nameNe: "शहीद दिवस",
    tradition: "civic", bs: [2081, 10, 16], ad: [2025, 1, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "sonam-lhosar-2081", group: "sonam-lhosar",
    nameEn: "Sonam Lhosar", nameNe: "सोनाम ल्होसार",
    tradition: "buddhist", bs: [2081, 10, 17], ad: [2025, 1, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "saraswati-puja-2081", group: "saraswati-puja",
    nameEn: "Saraswati Puja", nameNe: "सरस्वती पूजा",
    tradition: "hindu", bs: [2081, 10, 21], ad: [2025, 2, 3],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "skanda-shashti-2081", group: "skanda-shashti",
    nameEn: "Skanda Shashti", nameNe: "स्कन्द षष्ठी",
    tradition: "hindu", bs: [2081, 10, 22], ad: [2025, 2, 4],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "prajatantra-diwas-2081", group: "prajatantra-diwas",
    nameEn: "Prajatantra Diwas", nameNe: "प्रजातन्त्र दिवस",
    tradition: "civic", bs: [2081, 11, 7], ad: [2025, 2, 19],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "army-day-2081", group: "army-day",
    nameEn: "Army Day", nameNe: "सेना दिवस",
    tradition: "civic", bs: [2081, 11, 14], ad: [2025, 2, 26],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maha-shivaratri-2081", group: "maha-shivaratri",
    nameEn: "Maha Shivaratri", nameNe: "महा शिवरात्रि",
    tradition: "hindu", bs: [2081, 11, 14], ad: [2025, 2, 26],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gyalpo-lhosar-2081", group: "gyalpo-lhosar",
    nameEn: "Gyalpo Lhosar", nameNe: "ग्याल्पो ल्होसार",
    tradition: "buddhist", bs: [2081, 11, 16], ad: [2025, 2, 28],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "women-s-day-2081", group: "womens-day",
    nameEn: "Women's Day", nameNe: "नारी दिवस",
    tradition: "civic", bs: [2081, 11, 24], ad: [2025, 3, 8],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "holi-hills-2081", group: "holi",
    nameEn: "Holi (Hills)", nameNe: "होली (पहाड)",
    tradition: "hindu", bs: [2081, 11, 29], ad: [2025, 3, 13],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "holi-terai-2081", group: "holi",
    nameEn: "Holi (Terai)", nameNe: "होली (तराई)",
    tradition: "hindu", bs: [2081, 12, 1], ad: [2025, 3, 14],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gangaur-puja-2081", group: "gangaur",
    nameEn: "Gangaur Puja", nameNe: "गणगौर पूजा",
    tradition: "hindu", bs: [2081, 12, 2], ad: [2025, 3, 15],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "pahan-chahre-2081", group: "pahan-chahre",
    nameEn: "Pahan Chahre", nameNe: "पाहाँचःह्रे",
    tradition: "janajati", bs: [2081, 12, 15], ad: [2025, 3, 28],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "eid-al-fitr-2081", group: "eid-fitr",
    nameEn: "Eid al-Fitr", nameNe: "ईद अल-फित्र",
    tradition: "muslim", bs: [2081, 12, 18], ad: [2025, 3, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chaite-dashain-2081-2", group: "chaite-dashain",
    nameEn: "Chaite Dashain", nameNe: "चैते दशैं",
    tradition: "hindu", bs: [2081, 12, 23], ad: [2025, 4, 5],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ram-nawami-2081-2", group: "ram-nawami",
    nameEn: "Ram Nawami", nameNe: "रामनवमी",
    tradition: "hindu", bs: [2081, 12, 24], ad: [2025, 4, 6],
    contextEn: "",
    contextNe: "",
  },
];
