/**
 * Festivals of BS 2082 — imported from the Hamro Patro-based community
 * feed (shresthasushil NepaliEvents.ics), major public observances only.
 * Routine vrats, sankrantis, shraddhas, saint jayantis, valley-only jatras
 * and international days are skipped by design.
 *
 * Regenerate with: node scripts/fetch-nepali-events.mjs [ics-path] --write
 *
 * Conventions match festivals-2083.ts, except context lines are empty:
 * one-line writeups stay human-written per year. The Samiti file owns 2083;
 * this importer never emits 2083 rows.
 */
import type { FestivalEntry } from "./festivals-2083";

export const FESTIVALS_2082: FestivalEntry[] = [
  {
    slug: "nepali-new-year-2082", group: "new-year",
    nameEn: "Nepali New Year", nameNe: "नयाँ वर्ष",
    tradition: "civic", bs: [2082, 1, 1], ad: [2025, 4, 14],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "loktantra-diwas-2082", group: "loktantra-diwas",
    nameEn: "Loktantra Diwas", nameNe: "लोकतन्त्र दिवस",
    tradition: "civic", bs: [2082, 1, 11], ad: [2025, 4, 24],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "mata-tirtha-aunsi-2082", group: "mata-tirtha-aunsi",
    nameEn: "Mata Tirtha Aunsi", nameNe: "मातातीर्थ औंसी",
    tradition: "hindu", bs: [2082, 1, 14], ad: [2025, 4, 27],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "akshaya-tritiya-2082", group: "akshaya-tritiya",
    nameEn: "Akshaya Tritiya", nameNe: "अक्षय तृतीया",
    tradition: "hindu", bs: [2082, 1, 17], ad: [2025, 4, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "buddha-jayanti-2082", group: "buddha-jayanti",
    nameEn: "Buddha Jayanti", nameNe: "बुद्ध जयन्ती",
    tradition: "buddhist", bs: [2082, 1, 29], ad: [2025, 5, 12],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ubhauli-2082", group: "ubhauli",
    nameEn: "Ubhauli", nameNe: "उभौली",
    tradition: "janajati", bs: [2082, 1, 29], ad: [2025, 5, 12],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "sithi-chahre-2082", group: "sithi-chahre",
    nameEn: "Sithi Chahre", nameNe: "सिथि चःह्रे",
    tradition: "janajati", bs: [2082, 2, 11], ad: [2025, 5, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "republic-day-2082", group: "prajatantra-diwas",
    nameEn: "Republic Day", nameNe: "गणतन्त्र दिवस",
    tradition: "civic", bs: [2082, 2, 15], ad: [2025, 5, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "sithi-nakha-2082", group: "sithi-chahre",
    nameEn: "Sithi Nakha", nameNe: "सिथि नख:",
    tradition: "janajati", bs: [2082, 2, 18], ad: [2025, 6, 1],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "eid-al-adha-2082", group: "eid-adha",
    nameEn: "Eid al-Adha", nameNe: "ईद अल-अधा",
    tradition: "muslim", bs: [2082, 2, 24], ad: [2025, 6, 7],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "bhumi-puja-2082", group: "bhumi-puja",
    nameEn: "Bhumi Puja", nameNe: "भूमि पूजा",
    tradition: "hindu", bs: [2082, 3, 11], ad: [2025, 6, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maghe-sankranti-2082-2", group: "maghe-sankranti",
    nameEn: "Maghe Sankranti", nameNe: "माघे संक्रान्ति",
    tradition: "hindu", bs: [2082, 3, 15], ad: [2025, 6, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gathamuga-chahre-2082", group: "gathamuga",
    nameEn: "Gathamuga Chahre", nameNe: "गथांमुगः चःह्रे",
    tradition: "janajati", bs: [2082, 4, 7], ad: [2025, 7, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "nag-panchami-2082", group: "nag-panchami",
    nameEn: "Nag Panchami", nameNe: "नागपञ्चमी",
    tradition: "hindu", bs: [2082, 4, 13], ad: [2025, 7, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kheer-khane-din-2082", group: "kheer-khane",
    nameEn: "Kheer Khane Din", nameNe: "खीर खाने दिन",
    tradition: "hindu", bs: [2082, 4, 15], ad: [2025, 7, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "raksha-bandhan-2082", group: "raksha-bandhan",
    nameEn: "Raksha Bandhan", nameNe: "रक्षाबन्धन",
    tradition: "hindu", bs: [2082, 4, 24], ad: [2025, 8, 9],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "krishna-janmashtami-2082", group: "krishna-janmashtami",
    nameEn: "Krishna Janmashtami", nameNe: "कृष्ण जन्माष्टमी",
    tradition: "hindu", bs: [2082, 4, 31], ad: [2025, 8, 16],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kushe-aunsi-2082", group: "kushe-aunsi",
    nameEn: "Kushe Aunsi", nameNe: "कुशे औंसी",
    tradition: "hindu", bs: [2082, 5, 7], ad: [2025, 8, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "dar-khane-teej-eve-2082", group: "teej",
    nameEn: "Dar Khane (Teej Eve)", nameNe: "दर खाने दिन",
    tradition: "hindu", bs: [2082, 5, 9], ad: [2025, 8, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "haritalika-teej-2082", group: "teej",
    nameEn: "Haritalika Teej", nameNe: "हरितालिका तीज",
    tradition: "hindu", bs: [2082, 5, 10], ad: [2025, 8, 26],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ganesh-chaturthi-2082", group: "ganesh-chaturthi",
    nameEn: "Ganesh Chaturthi", nameNe: "गणेश चतुर्थी",
    tradition: "hindu", bs: [2082, 5, 11], ad: [2025, 8, 27],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chhath-parva-2082-2", group: "chhath",
    nameEn: "Chhath Parva", nameNe: "छठ पर्व",
    tradition: "hindu", bs: [2082, 5, 11], ad: [2025, 8, 27],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "rishi-panchami-2082", group: "teej",
    nameEn: "Rishi Panchami", nameNe: "ऋषि पञ्चमी",
    tradition: "hindu", bs: [2082, 5, 12], ad: [2025, 8, 28],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chhath-parva-2082", group: "chhath",
    nameEn: "Chhath Parva", nameNe: "छठ पर्व",
    tradition: "hindu", bs: [2082, 5, 13], ad: [2025, 8, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gaura-saptami-2082", group: "gaura",
    nameEn: "Gaura Saptami", nameNe: "गौरा सप्तमी",
    tradition: "janajati", bs: [2082, 5, 14], ad: [2025, 8, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gaura-festival-2082", group: "gaura",
    nameEn: "Gaura Festival", nameNe: "गौरा पर्व",
    tradition: "janajati", bs: [2082, 5, 15], ad: [2025, 8, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "durva-ashtami-2082", group: "durva-ashtami",
    nameEn: "Durva Ashtami", nameNe: "दुर्वाष्टमी",
    tradition: "hindu", bs: [2082, 5, 15], ad: [2025, 8, 31],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ananta-chaturdashi-2082", group: "ananta-chaturdashi",
    nameEn: "Ananta Chaturdashi", nameNe: "अनन्त चतुर्दशी",
    tradition: "hindu", bs: [2082, 5, 21], ad: [2025, 9, 6],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "jitiya-parva-2082", group: "jitiya",
    nameEn: "Jitiya Parva", nameNe: "जितिया पर्व",
    tradition: "janajati", bs: [2082, 5, 30], ad: [2025, 9, 15],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gen-z-andolan-mourning-2082", group: "genz-andolan",
    nameEn: "Gen Z Andolan Mourning", nameNe: "जेनजी आन्दोलन शोक",
    tradition: "civic", bs: [2082, 6, 1], ad: [2025, 9, 17],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "constitution-day-2082", group: "constitution-day",
    nameEn: "Constitution Day", nameNe: "संविधान दिवस",
    tradition: "civic", bs: [2082, 6, 3], ad: [2025, 9, 19],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "pitri-visarjan-2082", group: "pitri-paksha",
    nameEn: "Pitri Visarjan", nameNe: "पितृ विसर्जन",
    tradition: "hindu", bs: [2082, 6, 5], ad: [2025, 9, 21],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ghatasthapana-2082", group: "dashain",
    nameEn: "Ghatasthapana", nameNe: "घटस्थापना",
    tradition: "hindu", bs: [2082, 6, 6], ad: [2025, 9, 22],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "phulpati-2082", group: "dashain",
    nameEn: "Phulpati", nameNe: "फूलपाती",
    tradition: "hindu", bs: [2082, 6, 13], ad: [2025, 9, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maha-ashtami-2082", group: "dashain",
    nameEn: "Maha Ashtami", nameNe: "महा अष्टमी",
    tradition: "hindu", bs: [2082, 6, 14], ad: [2025, 9, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maha-navami-2082", group: "dashain",
    nameEn: "Maha Navami", nameNe: "महा नवमी",
    tradition: "hindu", bs: [2082, 6, 15], ad: [2025, 10, 1],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "devi-visarjan-2082", group: "dashain",
    nameEn: "Devi Visarjan", nameNe: "देवी विसर्जन",
    tradition: "hindu", bs: [2082, 6, 16], ad: [2025, 10, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "vijaya-dashami-2082", group: "dashain",
    nameEn: "Vijaya Dashami", nameNe: "विजया दशमी",
    tradition: "hindu", bs: [2082, 6, 16], ad: [2025, 10, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "dhanteras-2082", group: "tihar",
    nameEn: "Dhanteras", nameNe: "धनतेरस",
    tradition: "hindu", bs: [2082, 7, 1], ad: [2025, 10, 18],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kag-tihar-2082", group: "tihar",
    nameEn: "Kag Tihar", nameNe: "काग तिहार",
    tradition: "hindu", bs: [2082, 7, 2], ad: [2025, 10, 19],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "laxmi-puja-2082", group: "tihar",
    nameEn: "Laxmi Puja", nameNe: "लक्ष्मी पूजा",
    tradition: "hindu", bs: [2082, 7, 3], ad: [2025, 10, 20],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kukur-tihar-2082", group: "tihar",
    nameEn: "Kukur Tihar", nameNe: "कुकुर तिहार",
    tradition: "hindu", bs: [2082, 7, 3], ad: [2025, 10, 20],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "narak-chaturdashi-2082", group: "tihar",
    nameEn: "Narak Chaturdashi", nameNe: "नरक चतुर्दशी",
    tradition: "hindu", bs: [2082, 7, 3], ad: [2025, 10, 20],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gai-tihar-2082", group: "tihar",
    nameEn: "Gai Tihar", nameNe: "गाई तिहार",
    tradition: "hindu", bs: [2082, 7, 5], ad: [2025, 10, 22],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gobardhan-puja-2082", group: "tihar",
    nameEn: "Gobardhan Puja", nameNe: "गोवर्धन पूजा",
    tradition: "hindu", bs: [2082, 7, 5], ad: [2025, 10, 22],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "hali-tihar-2082", group: "tihar",
    nameEn: "Hali Tihar", nameNe: "हलि तिहार",
    tradition: "hindu", bs: [2082, 7, 5], ad: [2025, 10, 22],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "nepal-sambat-new-year-2082", group: "nepal-sambat",
    nameEn: "Nepal Sambat New Year", nameNe: "नेपाल संवत् नयाँ वर्ष",
    tradition: "janajati", bs: [2082, 7, 5], ad: [2025, 10, 22],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "mha-puja-2082", group: "tihar",
    nameEn: "Mha Puja", nameNe: "म्ह पूजा",
    tradition: "janajati", bs: [2082, 7, 5], ad: [2025, 10, 22],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "kija-puja-2082", group: "tihar",
    nameEn: "Kija Puja", nameNe: "किजा पूजा",
    tradition: "janajati", bs: [2082, 7, 6], ad: [2025, 10, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "bhai-tika-2082", group: "tihar",
    nameEn: "Bhai Tika", nameNe: "भाइ टीका",
    tradition: "hindu", bs: [2082, 7, 6], ad: [2025, 10, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chhath-parva-2082-3", group: "chhath",
    nameEn: "Chhath Parva", nameNe: "छठ पर्व",
    tradition: "hindu", bs: [2082, 7, 10], ad: [2025, 10, 27],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gopashtami-2082", group: "gopashtami",
    nameEn: "Gopashtami", nameNe: "गोपाष्टमी",
    tradition: "hindu", bs: [2082, 7, 12], ad: [2025, 10, 29],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "bala-chaturdashi-2082", group: "bala-chaturdashi",
    nameEn: "Bala Chaturdashi", nameNe: "बाला चतुर्दशी",
    tradition: "hindu", bs: [2082, 8, 3], ad: [2025, 11, 19],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "vivah-panchami-2082", group: "vivah-panchami",
    nameEn: "Vivah Panchami", nameNe: "विवाह पञ्चमी",
    tradition: "hindu", bs: [2082, 8, 9], ad: [2025, 11, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "gita-jayanti-2082", group: "gita-jayanti",
    nameEn: "Gita Jayanti", nameNe: "गीता जयन्ती",
    tradition: "hindu", bs: [2082, 8, 15], ad: [2025, 12, 1],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "dhanya-purnima-2082", group: "udhauli",
    nameEn: "Dhanya Purnima", nameNe: "धान्य पूर्णिमा",
    tradition: "janajati", bs: [2082, 8, 18], ad: [2025, 12, 4],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "udhauli-2082", group: "udhauli",
    nameEn: "Udhauli", nameNe: "उधौली",
    tradition: "janajati", bs: [2082, 8, 18], ad: [2025, 12, 4],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "jyapu-day-2082", group: "udhauli",
    nameEn: "Jyapu Day", nameNe: "ज्यापू दिवस",
    tradition: "janajati", bs: [2082, 8, 18], ad: [2025, 12, 4],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "tol-lhosar-2082", group: "tol-lhosar",
    nameEn: "Tol Lhosar", nameNe: "तोल ल्होसार",
    tradition: "janajati", bs: [2082, 9, 5], ad: [2025, 12, 20],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "christmas-day-2082", group: "christmas",
    nameEn: "Christmas Day", nameNe: "क्रिसमस डे",
    tradition: "christian", bs: [2082, 9, 10], ad: [2025, 12, 25],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "tamu-lhosar-2082", group: "tamu-lhosar",
    nameEn: "Tamu Lhosar", nameNe: "तमु ल्होसार",
    tradition: "janajati", bs: [2082, 9, 15], ad: [2025, 12, 30],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "topi-diwas-2082", group: "topi-diwas",
    nameEn: "Topi Diwas", nameNe: "टोपी दिवस",
    tradition: "civic", bs: [2082, 9, 17], ad: [2026, 1, 1],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "nepali-new-year-2082-2", group: "new-year",
    nameEn: "Nepali New Year", nameNe: "नयाँ वर्ष",
    tradition: "civic", bs: [2082, 9, 17], ad: [2026, 1, 1],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "prithvi-jayanti-2082", group: "prithvi-jayanti",
    nameEn: "Prithvi Jayanti", nameNe: "पृथ्वी जयन्ती",
    tradition: "civic", bs: [2082, 9, 27], ad: [2026, 1, 11],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "maghe-sankranti-2082", group: "maghe-sankranti",
    nameEn: "Maghe Sankranti", nameNe: "माघे संक्रान्ति",
    tradition: "hindu", bs: [2082, 10, 1], ad: [2026, 1, 15],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "saraswati-puja-2082", group: "saraswati-puja",
    nameEn: "Saraswati Puja", nameNe: "सरस्वती पूजा",
    tradition: "hindu", bs: [2082, 10, 9], ad: [2026, 1, 23],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "skanda-shashti-2082", group: "skanda-shashti",
    nameEn: "Skanda Shashti", nameNe: "स्कन्द षष्ठी",
    tradition: "hindu", bs: [2082, 10, 10], ad: [2026, 1, 24],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "army-day-2082", group: "army-day",
    nameEn: "Army Day", nameNe: "सेना दिवस",
    tradition: "civic", bs: [2082, 11, 3], ad: [2026, 2, 15],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "holi-hills-2082", group: "holi",
    nameEn: "Holi (Hills)", nameNe: "होली (पहाड)",
    tradition: "hindu", bs: [2082, 11, 18], ad: [2026, 3, 2],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "holi-terai-2082", group: "holi",
    nameEn: "Holi (Terai)", nameNe: "होली (तराई)",
    tradition: "hindu", bs: [2082, 11, 19], ad: [2026, 3, 3],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "women-s-day-2082", group: "womens-day",
    nameEn: "Women's Day", nameNe: "नारी दिवस",
    tradition: "civic", bs: [2082, 11, 24], ad: [2026, 3, 8],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "pahan-chahre-2082", group: "pahan-chahre",
    nameEn: "Pahan Chahre", nameNe: "पाहाँचःह्रे",
    tradition: "janajati", bs: [2082, 12, 3], ad: [2026, 3, 17],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "chaite-dashain-2082", group: "chaite-dashain",
    nameEn: "Chaite Dashain", nameNe: "चैते दशैं",
    tradition: "hindu", bs: [2082, 12, 12], ad: [2026, 3, 26],
    contextEn: "",
    contextNe: "",
  },
  {
    slug: "ram-nawami-2082", group: "ram-nawami",
    nameEn: "Ram Nawami", nameNe: "रामनवमी",
    tradition: "hindu", bs: [2082, 12, 13], ad: [2026, 3, 27],
    contextEn: "",
    contextNe: "",
  },
];
