-- ═══════════════════════════════════════════════════════════════════
-- Pending Migrations Patch
-- Generated by ponytail: minimal changes needed for the app to work
--
-- Run this ONCE in your Supabase Dashboard SQL Editor.
-- ═══════════════════════════════════════════════════════════════════

-- 1. Add auth0_user_id column to profiles (if missing)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS auth0_user_id TEXT;
COMMENT ON COLUMN profiles.auth0_user_id IS 'Auth0 user ID for authentication';

-- 2. Create feedback table (if missing)
CREATE TABLE IF NOT EXISTS feedback (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL DEFAULT '',
  email       text,
  category    text NOT NULL DEFAULT 'bug' CHECK (category IN ('bug', 'feature', 'improvement', 'other')),
  message     text NOT NULL CHECK (char_length(message) >= 3),
  page_url    text,
  user_agent  text,
  auth0_user_id text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Enable RLS on feedback
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert feedback
CREATE POLICY IF NOT EXISTS "Anyone can insert feedback" ON feedback
  FOR INSERT WITH CHECK (true);

-- Allow maintainers to read feedback
DROP POLICY IF EXISTS "Maintainers can read feedback" ON feedback;
CREATE POLICY "Maintainers can read feedback" ON feedback
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.auth0_user_id = current_setting('request.jwt.claims')::json->>'sub'
        AND profiles.role = 'maintainer'
    )
  );

-- 3. Refresh PostgREST schema cache (required after adding columns to existing tables)
--    Run this if the feedback 'category' column still returns PGRST204:
--    NOTIFY pgrst, 'reload schema';
