import React from 'react';

import { notFound } from "next/navigation";
import { buildPageMetadata } from "@/lib/seo";
import { TrendingUp, Award, Globe, Calendar, CheckCircle2 } from "lucide-react";

import { getImpactReport } from "@/lib/actions/impact";

export const dynamic = "force-dynamic";

type Props = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: Props): Promise<unknown> {
  const { id } = await params;
  const report = await getImpactReport(id);
  
  if (!report) {
    return buildPageMetadata({ title: "Report Not Found", description: "The requested impact report could not be found.", path: `/projects/impact/${id}` });
  }

  return buildPageMetadata({
    title: `${report.projects.title} - Impact Report`,
    description: `Official impact report for ${report.projects.title} with an impact score of ${report.score}.`,
    path: `/projects/impact/${id}`,
  });
}

export default async function ImpactReportPage({ params }: Props) {
  const { id } = await params;
  const report = await getImpactReport(id);

  if (!report) {
    notFound();
  }

  const { projects: project } = report;
  const metrics = report.metrics;

  return (
    <div className="min-h-screen bg-background text-primary pt-24 pb-20 px-4">
      <div className="max-w-4xl mx-auto space-y-12">
        
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-bh-red-500/10 text-bh-red-500 text-xs font-bold uppercase tracking-widest border border-bh-red-500/20">
            <Award className="w-3 h-3" /> Official Impact Report
          </div>
          <h1 className="text-5xl md:text-7xl font-black tracking-tight font-heading">
            {project.title}
          </h1>
          <p className="text-lg text-secondary max-w-2xl mx-auto">
            Verified community impact snapshot generated on {new Date(report.generated_at).toLocaleDateString()}
          </p>
        </div>

        {/* Score Card */}
        <div className="relative group">
          <div className="absolute -inset-1 bg-gradient-to-r from-bh-red-500 to-accent-teal rounded-3xl blur opacity-25 group-hover:opacity-50 transition duration-1000"></div>
          <div className="relative lg-surface rounded-3xl p-12 border border-glass text-center space-y-6">
            <span className="text-xs font-mono uppercase tracking-widest text-secondary">Aggregate Impact Score</span>
            <div className="text-8xl md:text-9xl font-black text-primary tracking-tighter">
              {report.score}
            </div>
            <div className="flex justify-center gap-4">
              <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-surface/10 border border-glass text-xs font-medium">
                <CheckCircle2 className="w-4 h-4 text-green-400" />
                GitHub Verified
              </div>
              <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-surface/10 border border-glass text-xs font-medium">
                <Globe className="w-4 h-4 text-blue-400" />
                Global Reach
              </div>
            </div>
          </div>
        </div>

        {/* Detailed Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <MetricCard label="Views" value={metrics.views} icon={<TrendingUp className="w-5 h-5" />} color="text-blue-400" />
          <MetricCard label="Likes" value={metrics.likes} icon={<Award className="w-5 h-5" />} color="text-bh-red-500" />
          <MetricCard label="Comments" value={metrics.comments} icon={<Calendar className="w-5 h-5" />} color="text-teal-400" />
        </div>

        {/* Verification Section */}
        <div className="lg-surface rounded-3xl p-8 border border-glass space-y-4 text-center">
          <h3 className="text-lg font-bold">Verification Authenticity</h3>
          <p className="text-sm text-secondary max-w-xl mx-auto leading-relaxed">
            This report was generated by the Butwal Hacks automated impact engine. 
            It takes into account community engagement, developer contributions, and official verification.
          </p>
          <div className="pt-4">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-surface/10 border border-glass text-xs font-mono text-secondary">
              Report ID: {report.id}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function MetricCard({ label, value, icon, color }: { label: string; value: React.ReactNode; icon: React.ReactNode; color: string }) {
  return (
    <div className="lg-surface p-6 rounded-3xl border border-glass text-center space-y-2">
      <div className={`flex justify-center mb-2 ${color}`}>{icon}</div>
      <div className="text-3xl font-bold">{value}</div>
      <div className="text-xs font-mono uppercase tracking-widest text-secondary">{label}</div>
    </div>
  );
}
