-- Day 32: Project Showcase
--
-- SKIPPED: projects table already exists from 001_initial_schema.sql.
-- Creating it again here fails the whole chain with:
--   ERROR: relation "projects" already exists
-- The 001 definition is canonical (codebase uses its column names:
-- title, cover_image). Missing 032 columns (profile_id, hackathon_origin)
-- are backfilled by 086_consolidate_projects_schema.sql. See 086's header
-- for the full divergence analysis. This file is kept as a no-op marker
-- so migration numbering stays intact.
SELECT 1;
