-- ═══════════════════════════════════════════════════════════════════════
-- 085_fix_missing_columns.sql — Schema alignment for Auth0 + RBAC
-- ═══════════════════════════════════════════════════════════════════════
--
-- Fixes the following production issues:
--
-- 🔴 CRITICAL
--   1. profiles.auth0_user_id missing — used in 104+ places across the
--      codebase for Auth0 session-to-profile lookups. All profile queries
--      (.eq('auth0_user_id', userId)) fail with 'column does not exist'.
--
-- 🟡 HIGH
--   2. profiles.role CHECK constraint missing 'sponsor' — Schema only allows
--      ('hacker','organizer','maintainer'), but the platform has a Sponsor
--      Portal and the auth-guard.ts hierarchy includes sponsor.
--
-- 🟡 MEDIUM
--   3. audit_logs missing service_role SELECT grant — Dashboard activity feed
--      crashes with 'permission denied for table audit_logs'. The grant in
--      migration 055 may not have been applied.
--
-- All statements use IF NOT EXISTS / IF EXISTS so they are safe to re-run.
-- ═══════════════════════════════════════════════════════════════════════

-- ─── 1. Add auth0_user_id to profiles ──────────────────────────────────
-- This column is the link between Auth0 sessions and Supabase profiles.
-- It's queried in every server action and API route that needs the
-- current user's profile. Without it, no authenticated operation works.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS auth0_user_id text UNIQUE;

COMMENT ON COLUMN public.profiles.auth0_user_id IS
  'Auth0 user.sub value. Links Auth0 sessions to Supabase profiles.';

-- Add a partial index for faster lookups (most queries filter by this)
CREATE INDEX IF NOT EXISTS idx_profiles_auth0_user_id
  ON public.profiles(auth0_user_id)
  WHERE auth0_user_id IS NOT NULL;

-- ─── 2. Add social_links column (used by team-matching) ────────────────
-- The findTeammates() action queries profiles.social_links but the column
-- may not exist if migration 005 was skipped.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS social_links jsonb DEFAULT '{}'::jsonb;

-- ─── 3. Fix role CHECK constraint to include 'sponsor' ─────────────────
-- The initial schema's constraint doesn't allow 'sponsor'. We need to
-- drop the old constraint and recreate it with the full role set.

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('hacker', 'organizer', 'maintainer', 'sponsor'));

-- ─── 4. Grant SELECT on audit_logs to service_role ─────────────────────
-- Without this, the dashboard activity feed and maintainer audit log
-- crash with 'permission denied'. The grant was originally in migration
-- 055 but may not have been applied.

GRANT SELECT ON public.audit_logs TO service_role;

-- ─── 5. Drop the auth.users FK constraint ──────────────────────────────
-- The profiles table references auth.users which doesn't exist in this
-- Auth0-only setup. This FK prevents inserts from the Auth0 webhook.
-- We drop it since Auth0 (not Supabase Auth) manages authentication.

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_id_fkey;

COMMENT ON COLUMN public.profiles.id IS
  'UUID generated by the app (not from auth.users). Auth0 manages auth.';

-- ═══ Done ═════════════════════════════════════════════════════════════
